export default {
	// 身份
	identityOptions : [
		{ label: '应届生', value: 'graduate' },
		{ label: '当界应届生', value: 'current_graduate' },
		{ label: '往届应届生', value: 'previous_graduate' },
		{ label: '往界生', value: 'previous_student' }
	],
	// 政治面貌
	politicalOptions : [
		{ label: '不限', value: 'unlimited' },
		{ label: '共青团员', value: 'communist_youth_league' },
		{ label: '中共党员', value: 'communist_party_member' }
	],
	// 工作年限
	experienceOptions : [
		{ label: '不限', value: 'unlimited' },
		{ label: '一年', value: '1_year' },
		{ label: '二年', value: '2_years' },
		{ label: '三年', value: '3_years' },
		{ label: '五年以上', value: '5_years_above' }
	],
	// 学历
	educationOptions : [
		{ label: '大专及以上', value: 'college_above' },
		{ label: '本科及学士学位', value: 'bachelor_degree' }
	],
	// 学科
	disciplineOptions : [
		{ label: '哲学', value: 'philosophy' },
		{ label: '经济学', value: 'economics' },
		{ label: '法学', value: 'law' },
		{ label: '教育学', value: 'educationMajor' },
		{ label: '文学', value: 'literature' },
		{ label: '历史学', value: 'history' },
		{ label: '理学', value: 'science' },
		{ label: '工学', value: 'engineering' },
		{ label: '农学', value: 'agriculture' },
		{ label: '医学', value: 'medicine' },
		{ label: '军事学', value: 'military_science' },
		{ label: '管理学', value: 'management' }
	],
	// 经济学
	economicsOptions : [
		{ label: '经济学类（0201）', value: 'economics_0201' },
		{ label: '金融学类（0202）', value: 'finance_0202' },
		{ label: '财政学类（0203）', value: 'fiscal_science_0203' },
		{ label: '经济与贸易类（0204）', value: 'economy_trade_0204' }
	],
	// 法学
	lawOptions : [
		{ label: '法学类（0301）', value: 'law_0301' },
		{ label: '政治学类（0302）', value: 'political_science_0302' },
		{ label: '社会学类（0303）', value: 'sociology_0303' },
		{ label: '民族学类（0304）', value: 'ethnology_0304' },
		{ label: '马克思主义理论类（0305）', value: 'marxist_theory_0305' },
		{ label: '公安学类（0306）', value: 'public_security_0306' }
	],
	// 管理学
	managementOptions : [
		{ label: '工商管理类（1202）', value: 'business_management_1202' },
		{ label: '公共管理类（1204）', value: 'public_management_1204' },
		{ label: '电子商务类（1208）', value: 'e_commerce_1208' },
		{ label: '管理科学与工程类（1201）', value: 'management_science_1201' },
		{ label: '物流工程与管理类（1206）', value: 'logistics_management_1206' },
		{ label: '旅游管理类（1209）', value: 'tourism_management_1209' },
		{ label: '工业工程类（1207）', value: 'industrial_engineering_1207' },
		{ label: '农业经济管理类（1203）', value: 'agricultural_economics_1203' },
		{ label: '图书情报与档案管理类（1205）', value: 'library_archives_management_1205' }
	],
	// 文学
	literatureOptions : [
		{ label: '中国语言文学类（0501）', value: 'chinese_language_literature_0501' },
		{ label: '外国语言文学类（0502）', value: 'foreign_language_literature_0502' },
		{ label: '新闻传播学类（0503）', value: 'journalism_communication_0503' }
	],
	// 哲学
	philosophyOptions : [
		{ label: '哲学类（0101）', value: 'philosophy_0101' }
	],
	// 教育学
	educationMajorOptions : [
		{ label: '教育学类（0401）', value: 'education_0401' },
		{ label: '体育学类（0402）', value: 'physical_education_0402' }
	],
	// 艺术学
	artOptions : [
		{ label: '艺术学理论类（1301）', value: 'art_theory_1301' },
		{ label: '音乐与舞蹈类（1302）', value: 'music_dance_1302' },
		{ label: '戏剧与影视学类（1303）', value: 'theatre_film_1303' },
		{ label: '美术学类（1304）', value: 'fine_arts_1304' },
		{ label: '设计学类（1305）', value: 'design_1305' }
	],
	// 医学
	medicalOptions : [
		{ label: '基础医学类（1001）', value: 'basic_medicine_1001' },
		{ label: '临床医学类（1002）', value: 'clinical_medicine_1002' },
		{ label: '公共卫生与预防医学类（1004）', value: 'public_health_1004' },
		{ label: '中医学类（1005）', value: 'chinese_medicine_1005' },
		{ label: '中西医结合类（1006）', value: 'chinese_western_medicine_1006' },
		{ label: '法医学类（1009）', value: 'forensic_science_1009' },
		{ label: '医学技术类（1010）', value: 'medical_technology_1010' },
		{ label: '中药学类（可授予理学学位）（1008）', value: 'chinese_pharmacy_1008' },
		{ label: '药学类（可授予理学学位）（1007）', value: 'pharmacy_1007' },
		{ label: '口腔医学类（1003）', value: 'stomatology_1003' },
		{ label: '护理学类（1011）', value: 'nursing_1011' }
	],
	// 工学
	engineeringOptions : [
		{ label: '计算机类（0807）', value: 'computer_science_0807' },
		{ label: '电子信息类（0809）', value: 'electronic_information_0809' },
		{ label: '机械类（0802）', value: 'mechanical_engineering_0802' },
		{ label: '材料类（0804）', value: 'materials_science_0804' },
		{ label: '自动化类（0808）', value: 'automation_0808' },
		{ label: '仪器类（0803）', value: 'instrumentation_0803' },
		{ label: '电气类（0806）', value: 'electrical_engineering_0806' },
		{ label: '能源动力类（0805）', value: 'energy_power_0805' },
		{ label: '土木类（0810）', value: 'civil_engineering_0810' },
		{ label: '水利类（0811）', value: 'hydraulic_engineering_0811' },
		{ label: '测绘类（0812）', value: 'surveying_mapping_0812' },
		{ label: '化工与制药类（0813）', value: 'chemical_pharmaceutical_0813' },
		{ label: '地质类（0814）', value: 'geology_0814' },
		{ label: '矿业类（0815）', value: 'mining_engineering_0815' },
		{ label: '纺织类（0816）', value: 'textile_engineering_0816' },
		{ label: '轻工类（0817）', value: 'light_industry_0817' },
		{ label: '交通运输类（0818）', value: 'transportation_engineering_0818' },
		{ label: '海洋工程类（0819）', value: 'marine_engineering_0819' },
		{ label: '航空航天类（0820）', value: 'aerospace_engineering_0820' },
		{ label: '兵器类（0821）', value: 'weapons_engineering_0821' },
		{ label: '核工程类（0822）', value: 'nuclear_engineering_0822' },
		{ label: '农业工程类（0823）', value: 'agricultural_engineering_0823' },
		{ label: '林业工程类（0824）', value: 'forestry_engineering_0824' },
		{ label: '环境科学与工程类（0825）', value: 'environmental_engineering_0825' },
		{ label: '生物医学工程类（0826）', value: 'biomedical_engineering_0826' },
		{ label: '食品科学与工程类（0827）', value: 'food_science_engineering_0827' },
		{ label: '建筑类（0828）', value: 'architecture_0828' },
		{ label: '生物工程类（0830）', value: 'biological_engineering_0830' },
		{ label: '安全科学与工程类（0829）', value: 'safety_engineering_0829' },
		{ label: '公安技术类（0831）', value: 'public_security_technology_0831' }
	],
	// 理学
	scienceOptions : [
		{ label: '数学类（0701）', value: 'mathematics_0701' },
		{ label: '物理学类（0702）', value: 'physics_0702' },
		{ label: '化学类（0703）', value: 'chemistry_0703' },
		{ label: '地理科学类（0705）', value: 'geography_0705' },
		{ label: '大气科学类（0706）', value: 'atmospheric_science_0706' },
		{ label: '海洋科学类（0707）', value: 'marine_science_0707' },
		{ label: '力学类（0708）', value: 'mechanics_0708' },
		{ label: '生物科学类（0710）', value: 'biological_science_0710' },
		{ label: '天文学类（0704）', value: 'astronomy_0704' },
		{ label: '统计学类（0712）', value: 'statistics_0712' },
		{ label: '心理学类（0711）', value: 'psychology_0711' },
		{ label: '地质学类（0709）', value: 'geology_0709' },
		{ label: '电子信息科学类（0807）', value: 'electronic_information_science_0807' },
		{ label: '计算机科学与技术类（0807）', value: 'computer_science_0807' }
	],
	// 历史学
	historyOptions : [
		{ label: '历史学类（0601）', value: 'history_0601' }
	],
	// 农学
	agricultureOptions : [
		{ label: '植物生产类（0901）', value: 'plant_production_0901' },
		{ label: '自然保护与环境生态类（0902）', value: 'nature_conservation_0902' },
		{ label: '动物生产类（0903）', value: 'animal_production_0903' },
		{ label: '动物医学类（0904）', value: 'veterinary_medicine_0904' },
		{ label: '林学类（0905）', value: 'forestry_0905' },
		{ label: '水产类（0906）', value: 'aquaculture_0906' },
		{ label: '草学类（0907）', value: 'grassland_science_0907' }
	],
	// 机构性质
	jgOptions: [
		{label: '中央党群机关', value: '1'},
		{label: '中央国家行政机关（本级）', value: '2'},
		{label: '中央国家行政机关省级以下直属机构', value: '3'},
		{label: '中央国家行政机关参照公务员法管理事业单位', value: '4'}
	],
	// 考试类型
	ksOptions: [
		{label: '综合管理类A类', value: '1'},
		{label: '社会科学专技类B类', value: '2'},
		{label: '自然科学专技类C类', value: '3'},
		{label: '中小学教师类D类', value: '4'},
		{label: '医疗卫生类E类', value: '5'}
	],
	// 企业类型
	companyOptions: [
		{label: '国企', value: '1'},
		{label: '央企', value: '2'},
		{label: '民营', value: '3'},
		{label: '外资/合资企业', value: '4'},
		{label: '银行', value: '5'}
	],
	// 机构的二级
	jg_1_options: [
		{ label: '中央办公厅', value: '1' },
		{ label: '中央档案馆国家档案局', value: '2' },
		{ label: '中央组织部', value: '3' },
		{ label: '中央宣传部', value: '4' },
		{ label: '中央对外联络部', value: '5' },
		{ label: '中央台办', value: '6' },
		{ label: '中央财办', value: '7' },
		{ label: '中央和国家机关工委', value: '8' },
		{ label: '中央党史和文献研究院', value: '9' },
		{ label: '中国外文局', value: '10' },
		{ label: '中国浦东干部学院', value: '11' },
		{ label: '中国井冈山干部学院', value: '12' },
		{ label: '中国延安干部学院', value: '13' },
		{ label: '全国人大', value: '14' },
		{ label: '全国政协', value: '15' },
		{ label: '最高人民法院', value: '16' },
		{ label: '民建中央', value: '17' },
		{ label: '民进中央', value: '18' },
		{ label: '全国总工会', value: '19' },
		{ label: '全国妇联', value: '20' },
		{ label: '中国文联', value: '21' },
		{ label: '中国科协', value: '22' },
		{ label: '中国记协', value: '23' },
		{ label: '中国贸促会', value: '24' },
		{ label: '中国残联', value: '25' },
		{ label: '中国法学会', value: '26' },
		{ label: '中央社会主义学院', value: '27' },
		{ label: '中国藏学研究中心', value: '28' },
		{ label: '中央网信办', value: '29' }
	],
	jg_2_options: [
		{ label: '外交部', value: '1' },
		{ label: '国家发展和改革委员会', value: '2' },
		{ label: '教育部', value: '3' },
		{ label: '科学技术部', value: '4' },
		{ label: '工业和信息化部', value: '5' },
		{ label: '国家民族事务委员会', value: '6' },
		{ label: '公安部', value: '7' },
		{ label: '司法部', value: '8' },
		{ label: '人力资源和社会保障部', value: '9' },
		{ label: '生态环境部', value: '10' },
		{ label: '住房和城乡建设部', value: '11' },
		{ label: '交通运输部', value: '12' },
		{ label: '水利部', value: '13' },
		{ label: '农业农村部', value: '14' },
		{ label: '商务部', value: '15' },
		{ label: '文化和旅游部', value: '16' },
		{ label: '国家卫生健康委员会', value: '17' },
		{ label: '应急管理部', value: '18' },
		{ label: '审计署', value: '19' },
		{ label: '国务院国有资产监管管理委员会', value: '20' },
		{ label: '国家税务总局', value: '21' },
		{ label: '国家市场监督管理总局', value: '22' },
		{ label: '国家金融监督管理总局', value: '23' },
		{ label: '中国证券监督管理委员会', value: '24' },
		{ label: '国家广播电视总局', value: '25' },
		{ label: '国家统计局', value: '26' },
		{ label: '国务院参事室', value: '27' },
		{ label: '国家机关事务管理局', value: '28' },
		{ label: '国家粮食和物资储备局', value: '29' },
		{ label: '国家能源局', value: '30' },
		{ label: '国家数据局', value: '31' },
		{ label: '国家国防科技工业局', value: '32' },
		{ label: '国家林业和草原局', value: '33' },
		{ label: '中国民用航空局', value: '34' },
		{ label: '国家文物局', value: '35' },
		{ label: '国家中医药管理局', value: '36' },
		{ label: '国家疾病预防控制局', value: '37' },
		{ label: '国家药品监督管理局', value: '38' }
	],
	jg_3_options: [
		{ label: '天津市通信管理局', value: '1' },
		{ label: '江西省通信管理局', value: '2' },
		{ label: '湖南省通信管理局', value: '3' },
		{ label: '广东省通信管理局', value: '4' },
		{ label: '广西壮族自治区通信管理局', value: '5' },
		{ label: '西藏自治区通信管理局', value: '6' },
		{ label: '哈尔滨铁路公安局', value: '7' },
		{ label: '沈阳铁路公安局', value: '8' },
		{ label: '北京铁路公安局', value: '9' },
		{ label: '太原铁路公安局', value: '10' },
		{ label: '呼和浩特铁路公安局', value: '11' },
		{ label: '郑州铁路公安局', value: '12' },
		{ label: '武汉铁路公安局', value: '13' },
		{ label: '西安铁路公安局', value: '14' },
		{ label: '济南铁路公安局', value: '15' },
		{ label: '上海铁路公安局', value: '16' },
		{ label: '南昌铁路公安局', value: '17' },
		{ label: '广州铁路公安局', value: '18' },
		{ label: '南宁铁路公安局', value: '19' },
		{ label: '成都铁路公安局', value: '20' },
		{ label: '昆明铁路公安局', value: '21' },
		{ label: '兰州铁路公安局', value: '22' },
		{ label: '乌鲁木齐铁路公安局', value: '23' },
		{ label: '青藏铁路公安局', value: '24' },
		{ label: '中国民用航空华北地区管理局公安局', value: '25' },
		{ label: '中国民用航空华东地区管理局公安局', value: '26' },
		{ label: '中国民用航空中南地区管理局公安局', value: '27' },
		{ label: '中国民用航空新疆管理局公安局', value: '28' },
		{ label: '中国民用航空西藏自治区管理局公安局', value: '29' },
		{ label: '首都机场公安局', value: '30' },
		{ label: '北京海关缉私局', value: '31' },
		{ label: '呼和浩特海关缉私局', value: '32' },
		{ label: '满洲里海关缉私局', value: '33' },
		{ label: '大连海关缉私局', value: '34' },
		{ label: '长春海关缉私局', value: '35' },
		{ label: '哈尔滨海关缉私局', value: '36' },
		{ label: '上海海关缉私局', value: '37' },
		{ label: '南京海关缉私局', value: '38' },
		{ label: '杭州海关缉私局', value: '39' },
		{ label: '福州海关缉私局', value: '40' },
		{ label: '厦门海关缉私局', value: '41' },
		{ label: '青岛海关缉私局', value: '42' },
		{ label: '广州海关缉私局', value: '43' },
		{ label: '深圳海关缉私局', value: '44' },
		{ label: '拱北海关缉私局', value: '45' },
		{ label: '黄埔海关缉私局', value: '46' },
		{ label: '江门海关缉私局', value: '47' },
		{ label: '湛江海关缉私局', value: '48' },
		{ label: '南宁海关缉私局', value: '49' },
		{ label: '海口海关缉私局', value: '50' },
		{ label: '昆明海关缉私局', value: '51' },
		{ label: '乌鲁木齐海关缉私局', value: '52' },
		{ label: '长江航运公安局', value: '53' },
		{ label: '司法部燕城监狱', value: '54' },
		{ label: '财政部北京监管局', value: '55' },
		{ label: '财政部河北监管局', value: '56' },
		{ label: '财政部山西监管局', value: '57' },
		{ label: '财政部内蒙古监管局', value: '58' },
		{ label: '财政部辽宁监管局', value: '59' },
		{ label: '财政部大连监管局', value: '60' },
		{ label: '财政部吉林监管局', value: '61' },
		{ label: '财政部黑龙江监管局', value: '62' },
		{ label: '财政部浙江监管局', value: '63' },
		{ label: '财政部安徽监管局', value: '64' },
		{ label: '财政部福建监管局', value: '65' },
		{ label: '财政部江西监管局', value: '66' },
		{ label: '财政部河南监管局', value: '67' },
		{ label: '财政部湖北监管局', value: '68' },
		{ label: '财政部湖南监管局', value: '69' },
		{ label: '财政部广东监管局', value: '70' },
		{ label: '财政部广西监管局', value: '71' },
		{ label: '财政部海南监管局', value: '72' },
		{ label: '财政部重庆监管局', value: '73' },
		{ label: '财政部四川监管局', value: '74' },
		{ label: '财政部贵州监管局', value: '75' },
		{ label: '财政部云南监管局', value: '76' },
		{ label: '财政部甘肃监管局', value: '77' },
		{ label: '财政部青海监管局', value: '78' },
		{ label: '财政部宁夏监管局', value: '79' },
		{ label: '国家自然资源督察北京局', value: '80' },
		{ label: '国家自然资源督察南京局', value: '81' },
		{ label: '国家自然资源督察广州局', value: '82' },
		{ label: '国家自然资源督察武汉局', value: '83' },
		{ label: '国家自然资源督察成都局', value: '84' },
		{ label: '国家自然资源督察西安局', value: '85' },
		{ label: '陕西测绘地理信息局', value: '86' },
		{ label: '四川测绘地理信息局', value: '87' },
		{ label: '海南测绘地理信息局', value: '88' },
		{ label: '自然资源部南海局', value: '89' },
		{ label: '生态环境部西北督察局', value: '90' },
		{ label: '生态环境部淮河流域生态环境监督管理局', value: '91' },
		{ label: '生态环境部珠江流域南海海域生态环境监督管理局', value: '92' },
		{ label: '生态环境部松辽流域生态环境监督管理局', value: '93' },
		{ label: '长江海事局', value: '94' },
		{ label: '江苏海事局', value: '95' },
		{ label: '上海海事局', value: '96' },
		{ label: '天津海事局', value: '97' },
		{ label: '辽宁海事局', value: '98' },
		{ label: '河北海事局', value: '99' },
		{ label: '山东海事局', value: '100' },
		{ label: '浙江海事局', value: '101' },
		{ label: '福建海事局', value: '102' },
		{ label: '广东海事局', value: '103' },
		{ label: '广西海事局', value: '104' },
		{ label: '海南海事局', value: '105' },
		{ label: '黑龙江海事局', value: '106' },
		{ label: '深圳海事局', value: '107' },
		{ label: '连云港海事局', value: '108' },
		{ label: '中国人民银行上海总部', value: '109' },
		{ label: '中国人民银行北京市分行', value: '110' },
		{ label: '中国人民银行天津市分行', value: '111' },
		{ label: '中国人民银行河北省分行', value: '112' },
		{ label: '中国人民银行山西省分行', value: '113' },
		{ label: '中国人民银行内蒙古自治区分行', value: '114' },
		{ label: '中国人民银行辽宁省分行', value: '115' },
		{ label: '中国人民银行吉林省分行', value: '116' },
		{ label: '中国人民银行黑龙江省分行', value: '117' },
		{ label: '中国人民银行江苏省分行', value: '118' },
		{ label: '中国人民银行浙江省分行', value: '119' },
		{ label: '中国人民银行安徽省分行', value: '120' },
		{ label: '中国人民银行福建省分行', value: '121' },
		{ label: '中国人民银行江西省分行', value: '122' },
		{ label: '中国人民银行山东省分行', value: '123' },
		{ label: '中国人民银行河南省分行', value: '124' },
		{ label: '中国人民银行湖北省分行', value: '125' },
		{ label: '中国人民银行湖南省分行', value: '126' },
		{ label: '中国人民银行广东省分行', value: '127' },
		{ label: '中国人民银行广西壮族自治区分行', value: '128' },
		{ label: '中国人民银行海南省分行', value: '129' },
		{ label: '中国人民银行重庆市分行', value: '130' },
		{ label: '中国人民银行四川省分行', value: '131' },
		{ label: '中国人民银行贵州省分行', value: '132' },
		{ label: '中国人民银行云南省分行', value: '133' },
		{ label: '中国人民银行西藏自治区分行', value: '134' },
		{ label: '中国人民银行陕西省分行', value: '135' },
		{ label: '中国人民银行甘肃省分行', value: '136' },
		{ label: '中国人民银行青海省分行', value: '137' },
		{ label: '中国人民银行宁夏回族自治区分行', value: '138' },
		{ label: '中国人民银行新疆维吾尔自治区分行', value: '139' },
		{ label: '中国人民银行大连市分行', value: '140' },
		{ label: '中国人民银行宁波市分行', value: '141' },
		{ label: '中国人民银行厦门市分行', value: '142' },
		{ label: '中国人民银行青岛市分行', value: '143' },
		{ label: '中国人民银行深圳市分行', value: '144' },
		{ label: '审计署京津冀特派员办事处', value: '145' },
		{ label: '审计署驻沈阳特派员办事处', value: '146' },
		{ label: '审计署驻上海特派员办事处', value: '147' },
		{ label: '审计署驻南京特派员办事处', value: '148' },
		{ label: '审计署驻武汉特派员办事处', value: '149' },
		{ label: '审计署驻广州特派员办事处', value: '150' },
		{ label: '审计署驻郑州特派员办事处', value: '151' },
		{ label: '审计署驻西安特派员办事处', value: '152' },
		{ label: '审计署驻昆明特派员办事处', value: '153' },
		{ label: '审计署驻长沙特派员办事处', value: '154' },
		{ label: '审计署驻深圳特派员办事处', value: '155' },
		{ label: '审计署驻重庆特派员办事处', value: '156' },
		{ label: '北京海关', value: '157' },
		{ label: '天津海关', value: '158' },
		{ label: '石家庄海关', value: '159' },
		{ label: '太原海关', value: '160' },
		{ label: '呼和浩特海关', value: '161' },
		{ label: '满洲里海关', value: '162' },
		{ label: '大连海关', value: '163' },
		{ label: '沈阳海关', value: '164' },
		{ label: '长春海关', value: '165' },
		{ label: '哈尔滨海关', value: '166' },
		{ label: '上海海关', value: '167' },
		{ label: '南京海关', value: '168' },
		{ label: '杭州海关', value: '169' },
		{ label: '宁波海关', value: '170' },
		{ label: '合肥海关', value: '171' },
		{ label: '福州海关', value: '172' },
		{ label: '厦门海关', value: '173' },
		{ label: '南昌海关', value: '174' },
		{ label: '青岛海关', value: '175' },
		{ label: '济南海关', value: '176' },
		{ label: '郑州海关', value: '177' },
		{ label: '武汉海关', value: '178' },
		{ label: '长沙海关', value: '179' },
		{ label: '广州海关', value: '180' },
		{ label: '深圳海关', value: '181' },
		{ label: '拱北海关', value: '182' },
		{ label: '汕头海关', value: '183' },
		{ label: '黄埔海关', value: '184' },
		{ label: '江门海关', value: '185' },
		{ label: '湛江海关', value: '186' },
		{ label: '南宁海关', value: '187' },
		{ label: '海口海关', value: '188' },
		{ label: '重庆海关', value: '189' },
		{ label: '成都海关', value: '190' },
		{ label: '贵阳海关', value: '191' },
		{ label: '昆明海关', value: '192' },
		{ label: '拉萨海关', value: '193' },
		{ label: '西安海关', value: '194' },
		{ label: '兰州海关', value: '195' },
		{ label: '西宁海关', value: '196' },
		{ label: '银川海关', value: '197' },
		{ label: '乌鲁木齐海关', value: '198' },
		{ label: '国家税务总局北京市税务局', value: '199' },
		{ label: '国家税务总局天津市税务局', value: '200' },
		{ label: '国家税务总局河北省税务局', value: '201' },
		{ label: '国家税务总局山西省税务局', value: '202' },
		{ label: '国家税务总局内蒙古自治区税务局', value: '203' },
		{ label: '国家税务总局辽宁省税务局', value: '204' },
		{ label: '国家税务总局大连市税务局', value: '205' },
		{ label: '国家税务总局吉林省税务局', value: '206' },
		{ label: '国家税务总局黑龙江省税务局', value: '207' },
		{ label: '国家税务总局上海市税务局', value: '208' },
		{ label: '国家税务总局江苏省税务局', value: '209' },
		{ label: '国家税务总局浙江省税务局', value: '210' },
		{ label: '国家税务总局宁波市税务局', value: '211' },
		{ label: '国家税务总局安徽省税务局', value: '212' },
		{ label: '国家税务总局福建省税务局', value: '213' },
		{ label: '国家税务总局厦门市税务局', value: '214' },
		{ label: '国家税务总局江西省税务局', value: '215' },
		{ label: '国家税务总局山东省税务局', value: '216' },
		{ label: '国家税务总局青岛市税务局', value: '217' },
		{ label: '国家税务总局河南省税务局', value: '218' },
		{ label: '国家税务总局湖北省税务局', value: '219' },
		{ label: '国家税务总局湖南省税务局', value: '220' },
		{ label: '国家税务总局广东省税务局', value: '221' },
		{ label: '国家税务总局深圳市税务局', value: '222' },
		{ label: '国家税务总局广西壮族自治区税务局', value: '223' },
		{ label: '国家税务总局海南省税务局', value: '224' },
		{ label: '国家税务总局重庆市税务局', value: '225' },
		{ label: '国家税务总局四川省税务局', value: '226' },
		{ label: '国家税务总局贵州省税务局', value: '227' },
		{ label: '国家税务总局云南省税务局', value: '228' },
		{ label: '国家税务总局西藏自治区税务局', value: '229' },
		{ label: '国家税务总局陕西省税务局', value: '230' },
		{ label: '国家税务总局甘肃省税务局', value: '231' },
		{ label: '国家税务总局青海省税务局', value: '232' },
		{ label: '国家税务总局宁夏回族自治区税务局', value: '233' },
		{ label: '国家税务总局新疆维吾尔自治区税务局', value: '234' },
		{ label: '国家金融监督管理总局北京监管局', value: '235' },
		{ label: '国家金融监督管理总局天津监管局', value: '236' },
		{ label: '国家金融监督管理总局河北监管局', value: '237' },
		{ label: '国家金融监督管理总局山西监管局', value: '238' },
		{ label: '国家金融监督管理总局内蒙古监管局', value: '239' },
		{ label: '国家金融监督管理总局辽宁监管局', value: '240' },
		{ label: '国家金融监督管理总局吉林监管局', value: '241' },
		{ label: '国家金融监督管理总局黑龙江监管局', value: '242' },
		{ label: '国家金融监督管理总局上海监管局', value: '243' },
		{ label: '国家金融监督管理总局江苏监管局', value: '244' },
		{ label: '国家金融监督管理总局浙江监管局', value: '245' },
		{ label: '国家金融监督管理总局安徽监管局', value: '246' },
		{ label: '国家金融监督管理总局福建监管局', value: '247' },
		{ label: '国家金融监督管理总局江西监管局', value: '248' },
		{ label: '国家金融监督管理总局山东监管局', value: '249' },
		{ label: '国家金融监督管理总局河南监管局', value: '250' },
		{ label: '国家金融监督管理总局湖北监管局', value: '251' },
		{ label: '国家金融监督管理总局湖南监管局', value: '252' },
		{ label: '国家金融监督管理总局广东监管局', value: '253' },
		{ label: '国家金融监督管理总局广西监管局', value: '254' },
		{ label: '国家金融监督管理总局海南监管局', value: '255' },
		{ label: '国家金融监督管理总局重庆监管局', value: '256' },
		{ label: '国家金融监督管理总局四川监管局', value: '257' },
		{ label: '国家金融监督管理总局贵州监管局', value: '258' },
		{ label: '国家金融监督管理总局云南监管局', value: '259' },
		{ label: '国家金融监督管理总局西藏监管局', value: '260' },
		{ label: '国家金融监督管理总局陕西监管局', value: '261' },
		{ label: '国家金融监督管理总局甘肃监管局', value: '262' },
		{ label: '国家金融监督管理总局青海监管局', value: '263' },
		{ label: '国家金融监督管理总局宁夏监管局', value: '264' },
		{ label: '国家金融监督管理总局新疆监管局', value: '265' },
		{ label: '国家金融监督管理总局大连监管局', value: '266' },
		{ label: '国家金融监督管理总局青岛监管局', value: '267' },
		{ label: '国家金融监督管理总局宁波监管局', value: '268' },
		{ label: '国家金融监督管理总局厦门监管局', value: '269' },
		{ label: '国家金融监督管理总局深圳监管局', value: '270' },
		{ label: '中国证券监督管理委员会北京监管局', value: '271' },
		{ label: '中国证券监督管理委员会天津监管局', value: '272' },
		{ label: '中国证券监督管理委员会河北监管局', value: '273' },
		{ label: '中国证券监督管理委员会山西监管局', value: '274' },
		{ label: '中国证券监督管理委员会内蒙古监管局', value: '275' },
		{ label: '中国证券监督管理委员会辽宁监管局', value: '276' },
		{ label: '中国证券监督管理委员会吉林监管局', value: '277' },
		{ label: '中国证券监督管理委员会黑龙江监管局', value: '278' },
		{ label: '中国证券监督管理委员会上海监管局', value: '279' },
		{ label: '中国证券监督管理委员会江苏监管局', value: '280' },
		{ label: '中国证券监督管理委员会浙江监管局', value: '281' },
		{ label: '中国证券监督管理委员会宁波监管局', value: '282' },
		{ label: '中国证券监督管理委员会安徽监管局', value: '283' },
		{ label: '中国证券监督管理委员会福建监管局', value: '284' },
		{ label: '中国证券监督管理委员会厦门监管局', value: '285' },
		{ label: '中国证券监督管理委员会山东监管局', value: '286' },
		{ label: '中国证券监督管理委员会青岛监管局', value: '287' },
		{ label: '中国证券监督管理委员会河南监管局', value: '288' },
		{ label: '中国证券监督管理委员会湖北监管局', value: '289' },
		{ label: '中国证券监督管理委员会湖南监管局', value: '290' },
		{ label: '中国证券监督管理委员会广东监管局', value: '291' },
		{ label: '中国证券监督管理委员会深圳监管局', value: '292' },
		{ label: '中国证券监督管理委员会广西监管局', value: '293' },
		{ label: '中国证券监督管理委员会海南监管局', value: '294' },
		{ label: '中国证券监督管理委员会四川监管局', value: '295' },
		{ label: '中国证券监督管理委员会重庆监管局', value: '296' },
		{ label: '中国证券监督管理委员会贵州监管局', value: '297' },
		{ label: '中国证券监督管理委员会云南监管局', value: '298' },
		{ label: '中国证券监督管理委员会西藏监管局', value: '299' },
		{ label: '中国证券监督管理委员会陕西监管局', value: '300' },
		{ label: '中国证券监督管理委员会甘肃监管局', value: '301' },
		{ label: '中国证券监督管理委员会宁夏监管局', value: '302' },
		{ label: '中国证券监督管理委员会青海监管局', value: '303' },
		{ label: '中国证券监督管理委员会新疆监管局', value: '304' },
		{ label: '中国证券监督管理委员会上海证券监管专员办事处', value: '305' },
		{ label: '中国证券监督管理委员会深圳证券监管专员办事处', value: '306' },
		{ label: '国家粮食和物资储备局河北局', value: '307' },
		{ label: '国家粮食和物资储备局内蒙古局', value: '308' },
		{ label: '国家粮食和物资储备局辽宁局', value: '309' },
		{ label: '国家粮食和物资储备局黑龙江局', value: '310' },
		{ label: '国家粮食和物资储备局山东局', value: '311' },
		{ label: '国家粮食和物资储备局湖北局', value: '312' },
		{ label: '国家粮食和物资储备局广东局', value: '313' },
		{ label: '国家粮食和物资储备局广西局', value: '314' },
		{ label: '国家粮食和物资储备局四川局', value: '315' },
		{ label: '国家粮食和物资储备局贵州局', value: '316' },
		{ label: '国家粮食和物资储备局云南局', value: '317' },
		{ label: '国家粮食和物资储备局陕西局', value: '318' },
		{ label: '国家粮食和物资储备局宁夏局', value: '319' },
		{ label: '国家粮食和物资储备局上海局', value: '320' },
		{ label: '国家粮食和物资储备局江苏局', value: '321' },
		{ label: '国家能源局华北监管局', value: '322' },
		{ label: '国家能源局东北监管局', value: '323' },
		{ label: '国家能源局西北监管局', value: '324' },
		{ label: '国家能源局华东监管局', value: '325' },
		{ label: '国家能源局华中监管局', value: '326' },
		{ label: '国家能源局南方监管局', value: '327' },
		{ label: '国家能源局山西监管办公室', value: '328' },
		{ label: '国家能源局甘肃监管办公室', value: '329' },
		{ label: '国家能源局浙江监管办公室', value: '330' },
		{ label: '国家能源局江苏监管办公室', value: '331' },
		{ label: '国家能源局福建监管办公室', value: '332' },
		{ label: '国家能源局湖南监管办公室', value: '333' },
		{ label: '国家能源局四川监管办公室', value: '334' },
		{ label: '国家能源局云南监管办公室', value: '335' },
		{ label: '国家能源局贵州监管办公室', value: '336' },
		{ label: '北京出入境边防检查总站', value: '337' },
		{ label: '天津出入境边防检查总站', value: '338' },
		{ label: '上海出入境边防检查总站', value: '339' },
		{ label: '广州出入境边防检查总站', value: '340' },
		{ label: '深圳出入境边防检查总站', value: '341' },
		{ label: '珠海出入境边防检查总站', value: '342' },
		{ label: '厦门出入境边防检查总站', value: '343' },
		{ label: '海口出入境边防检查总站', value: '344' },
		{ label: '山西出入境边防检查总站', value: '345' },
		{ label: '内蒙古出入境边防检查总站', value: '346' },
		{ label: '辽宁出入境边防检查总站', value: '347' },
		{ label: '吉林出入境边防检查总站', value: '348' },
		{ label: '黑龙江出入境边防检查总站', value: '349' },
		{ label: '江苏出入境边防检查总站', value: '350' },
		{ label: '浙江出入境边防检查总站', value: '351' },
		{ label: '安徽出入境边防检查总站', value: '352' },
		{ label: '山东出入境边防检查总站', value: '353' },
		{ label: '河南出入境边防检查总站', value: '354' },
		{ label: '湖北出入境边防检查总站', value: '355' },
		{ label: '湖南出入境边防检查总站', value: '356' },
		{ label: '广西出入境边防检查总站', value: '357' },
		{ label: '重庆出入境边防检查总站', value: '358' },
		{ label: '云南出入境边防检查总站', value: '359' },
		{ label: '西藏出入境边防检查总站', value: '360' },
		{ label: '陕西出入境边防检查总站', value: '361' },
		{ label: '甘肃出入境边防检查总站', value: '362' },
		{ label: '青海出入境边防检查总站', value: '363' },
		{ label: '新疆出入境边防检查总站', value: '364' },
		{ label: '国家移民管理局常备力量第一总队', value: '365' },
		{ label: '国家移民管理局常备力量第二总队', value: '366' },
		{ label: '国家移民管理局北京遣返中心', value: '367' },
		{ label: '国家移民管理局长春遣返中心', value: '368' },
		{ label: '国家移民管理局广州遣返中心', value: '369' },
		{ label: '国家移民管理局东兴遣返中心', value: '370' },
		{ label: '国家移民管理局瑞丽遣返中心', value: '371' },
		{ label: '沈阳铁路监督管理局', value: '372' },
		{ label: '武汉铁路监督管理局', value: '373' },
		{ label: '西安铁路监督管理局', value: '374' },
		{ label: '中国民用航空局华北地区管理局', value: '375' },
		{ label: '中国民用航空局华东地区管理局', value: '376' },
		{ label: '中国民用航空局中南地区管理局', value: '377' },
		{ label: '中国民用航空局西南地区管理局', value: '378' },
		{ label: '中国民用航空局西北地区管理局', value: '379' },
		{ label: '中国民用航空局东北地区管理局', value: '380' },
		{ label: '中国民用航空局新疆管理局', value: '381' },
		{ label: '北京市邮政管理局', value: '382' },
		{ label: '河北省邮政管理局', value: '383' },
		{ label: '山西省邮政管理局', value: '384' },
		{ label: '内蒙古自治区邮政管理局', value: '385' },
		{ label: '辽宁省邮政管理局', value: '386' },
		{ label: '吉林省邮政管理局', value: '387' },
		{ label: '黑龙江省邮政管理局', value: '388' },
		{ label: '上海市邮政管理局', value: '389' },
		{ label: '浙江省邮政管理局', value: '390' },
		{ label: '福建省邮政管理局', value: '391' },
		{ label: '江西省邮政管理局', value: '392' },
		{ label: '河南省邮政管理局', value: '393' },
		{ label: '湖南省邮政管理局', value: '394' },
		{ label: '广东省邮政管理局', value: '395' },
		{ label: '海南省邮政管理局', value: '396' },
		{ label: '重庆市邮政管理局', value: '397' },
		{ label: '四川省邮政管理局', value: '398' },
		{ label: '贵州省邮政管理局', value: '399' },
		{ label: '西藏自治区邮政管理局', value: '400' },
		{ label: '陕西省邮政管理局', value: '401' },
		{ label: '甘肃省邮政管理局', value: '402' },
		{ label: '新疆维吾尔自治区邮政管理局', value: '403' },
		{ label: '国家矿山安全监察局河北局', value: '404' },
		{ label: '国家矿山安全监察局山西局', value: '405' },
		{ label: '国家矿山安全监察局内蒙古局', value: '406'},
		{ label: '国家矿山安全监察局辽宁局', value: '407' },
		{ label: '国家矿山安全监察局吉林局', value: '408' },
		{ label: '国家矿山安全监察局黑龙江局', value: '409' },
		{ label: '国家矿山安全监察局江苏局', value: '410' },
		{ label: '国家矿山安全监察局安徽局', value: '411' },
		{ label: '国家矿山安全监察局江西局', value: '412' },
		{ label: '国家矿山安全监察局河南局', value: '413' },
		{ label: '国家矿山安全监察局湖南局', value: '414' },
		{ label: '国家矿山安全监察局广东局', value: '415' },
		{ label: '国家矿山安全监察局广西局', value: '416' },
		{ label: '国家矿山安全监察局四川局', value: '417' },
		{ label: '国家矿山安全监察局贵州局', value: '418' },
		{ label: '国家矿山安全监察局云南局', value: '419' },
		{ label: '国家矿山安全监察局陕西局', value: '420' },
		{ label: '国家矿山安全监察局甘肃局', value: '421' },
		{ label: '国家矿山安全监察局青海局', value: '422' },
		{ label: '国家矿山安全监察局宁夏局', value: '423' },
		{ label: '国家矿山安全监察局新疆局', value: '424' }
	],
	jg_4_options: [
		{ label: '科学技术部', value: '1' },
		{ label: '国家民族事务委员会', value: '2' },
		{ label: '公安部', value: '3' },
		{ label: '财政部', value: '4' },
		{ label: '人力资源和社会保障部', value: '5' },
		{ label: '生态环境部', value: '6' },
		{ label: '国家卫生健康委员会', value: '7' },
		{ label: '应急管理部', value: '8' },
		{ label: '国家税务总局', value: '9' },
		{ label: '国家统计局', value: '10' },
		{ label: '中国气象局', value: '11' },
		{ label: '国家粮食和物资储备局', value: '12' },
		{ label: '国家能源局', value: '13' },
		{ label: '国家国防科技工业局', value: '14' },
		{ label: '国家林业和草原局', value: '15' },
		{ label: '国家知识产权局', value: '16' },
		{ label: '中华全国供销合作总社', value: '17' },
		{ label: '中国地质调查局', value: '18' },
		{ label: '中国地震局', value: '19' },
		{ label: '司法部法律援助中心', value: '20' },
		{ label: '国家海洋局极地考察办公室', value: '21' },
		{ label: '水利部长江水利委员会', value: '22' },
		{ label: '水利部黄河水利委员会', value: '23' },
		{ label: '水利部淮河水利委员会', value: '24' },
		{ label: '水利部海河水利委员会', value: '25' },
		{ label: '水利部珠江水利委员会', value: '26' },
		{ label: '水利部松辽水利委员会', value: '27' },
		{ label: '水利部太湖流域管理局', value: '28' },
		{ label: '国家统计局北京调查总队', value: '29' },
		{ label: '国家统计局天津调查总队', value: '30' },
		{ label: '国家统计局河北调查总队', value: '31' },
		{ label: '国家统计局山西调查总队', value: '32' },
		{ label: '国家统计局内蒙古调查总队', value: '33' },
		{ label: '国家统计局辽宁调查总队', value: '34' },
		{ label: '国家统计局吉林调查总队', value: '35' },
		{ label: '国家统计局黑龙江调查总队', value: '36' },
		{ label: '国家统计局上海调查总队', value: '37' },
		{ label: '国家统计局江苏调查总队', value: '38' },
		{ label: '国家统计局浙江调查总队', value: '39' },
		{ label: '国家统计局安徽调查总队', value: '40' },
		{ label: '国家统计局福建调查总队', value: '41' },
		{ label: '国家统计局江西调查总队', value: '42' },
		{ label: '国家统计局山东调查总队', value: '43' },
		{ label: '国家统计局河南调查总队', value: '44' },
		{ label: '国家统计局湖北调查总队', value: '45' },
		{ label: '国家统计局湖南调查总队', value: '46' },
		{ label: '国家统计局广东调查总队', value: '47' },
		{ label: '国家统计局广西调查总队', value: '48' },
		{ label: '国家统计局海南调查总队', value: '49' },
		{ label: '国家统计局重庆调查总队', value: '50' },
		{ label: '国家统计局四川调查总队', value: '51' },
		{ label: '国家统计局贵州调查总队', value: '52' },
		{ label: '国家统计局云南调查总队', value: '53' },
		{ label: '国家统计局西藏调查总队', value: '54' },
		{ label: '国家统计局陕西调查总队', value: '55' },
		{ label: '国家统计局甘肃调查总队', value: '56' },
		{ label: '国家统计局青海调查总队', value: '57' },
		{ label: '国家统计局宁夏调查总队', value: '58' },
		{ label: '国家统计局新疆调查总队', value: '59' },
		{ label: '国家统计局新疆生产建设兵团调查总队', value: '60' },
		{ label: '北京市气象局', value: '61' },
		{ label: '河北省气象局', value: '62' },
		{ label: '山西省气象局', value: '63' },
		{ label: '内蒙古自治区气象局', value: '64' },
		{ label: '江苏省气象局', value: '65' },
		{ label: '浙江省气象局', value: '66' },
		{ label: '安徽省气象局', value: '67' },
		{ label: '福建省气象局', value: '68' },
		{ label: '江西省气象局', value: '69' },
		{ label: '山东省气象局', value: '70' },
		{ label: '河南省气象局', value: '71' },
		{ label: '湖北省气象局', value: '72' },
		{ label: '湖南省气象局', value: '73' },
		{ label: '广东省气象局', value: '74' },
		{ label: '广西壮族自治区气象局', value: '75' },
		{ label: '海南省气象局', value: '76' },
		{ label: '重庆市气象局', value: '77' },
		{ label: '四川省气象局', value: '78' },
		{ label: '贵州省气象局', value: '79' },
		{ label: '云南省气象局', value: '80' },
		{ label: '西藏自治区气象局', value: '81' },
		{ label: '陕西省气象局', value: '82' },
		{ label: '甘肃省气象局', value: '83' },
		{ label: '青海省气象局', value: '84' },
		{ label: '宁夏回族自治区气象局', value: '85' },
		{ label: '新疆维吾尔自治区气象局', value: '86' },
		{ label: '天津市地震局', value: '87' },
		{ label: '山西省地震局', value: '88' },
		{ label: '内蒙古自治区地震局', value: '89' },
		{ label: '吉林省地震局', value: '90' },
		{ label: '黑龙江省地震局', value: '91' },
		{ label: '浙江省地震局', value: '92' },
		{ label: '安徽省地震局', value: '93' },
		{ label: '江西省地震局', value: '94' },
		{ label: '山东省地震局', value: '95' },
		{ label: '河南省地震局', value: '96' },
		{ label: '湖北省地震局', value: '97' },
		{ label: '湖南省地震局', value: '98' },
		{ label: '广东省地震局', value: '99' },
		{ label: '广西壮族自治区地震局', value: '100' },
		{ label: '海南省地震局', value: '101' },
		{ label: '四川省地震局', value: '102' },
		{ label: '云南省地震局', value: '103' },
		{ label: '陕西省地震局', value: '104' },
		{ label: '甘肃省地震局', value: '105' },
		{ label: '青海省地震局', value: '106' },
		{ label: '宁夏回族自治区地震局', value: '107' },
		{ label: '新疆维吾尔自治区地震局', value: '108' },
		{ label: '生态环境部华北核与辐射安全监督站', value: '109' },
		{ label: '生态环境部华东核与辐射安全监督站', value: '110' },
		{ label: '生态环境部华南核与辐射安全监督站', value: '111' },
		{ label: '生态环境部西南核与辐射安全监督站', value: '112' },
		{ label: '生态环境部东北核与辐射安全监督站', value: '113' },
		{ label: '生态环境部西北核与辐射安全监督站', value: '114' }
	]
}
  
  